services:
  - type: web
    name: optombazar-backend
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: optombazar-db
          property: connectionString
      - key: GOOGLE_AI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PORT
        value: 10000

databases:
  - name: optombazar-db
    databaseName: optombazar
    user: optombazar_user
    plan: starter