import * as cron from 'node-cron';
import { generateBlogPost } from '../services/ai-content-generator';
import { sendBlogPostToChannel } from '../services/telegram-bot';
import type { IStorage } from '../storage';

let isSchedulerActive = false;

// Blog post yaratish va saqlash funksiyasi
async function createAndSaveBlogPost(storage: IStorage, language: 'uz' | 'ru' = 'uz'): Promise<void> {
  try {
    console.log(`${language.toUpperCase()} tilida yangi blog post yaratilmoqda...`);
    
    // AI orqali kontent yaratish
    const blogContent = await generateBlogPost(language, storage);
    
    // Ma'lumotlar bazasiga saqlash
    const blogPost = await storage.createBlogPost({
      title: blogContent.title,
      content: blogContent.content,
      excerpt: blogContent.excerpt,
      slug: blogContent.slug,
      tags: blogContent.tags,
      language: language,
      isAutoGenerated: true,
      source: 'AI-Generator',
      isPublished: true,
      imageUrl: null
    });

    console.log(`Blog post yaratildi va saqlandi: ${blogPost.title}`);

    // Telegram kanaliga yuborish
    try {
      await sendBlogPostToChannel({
        title: blogPost.title,
        content: blogPost.content,
        imageUrl: blogPost.imageUrl || undefined,
        url: `https://optommarket.uz/blog/${blogPost.slug}`
      });
      console.log('Blog post Telegram kanaliga yuborildi');
    } catch (telegramError) {
      console.error('Telegram kanaliga yuborishda xatolik:', telegramError);
    }

  } catch (error) {
    console.error('Blog post yaratishda xatolik:', error);
    throw error;
  }
}

// Yangi mahsulotlarni tekshirish va yuborish
async function checkAndSendNewProducts(storage: IStorage): Promise<void> {
  try {
    // Bugungi yangi mahsulotlarni olish
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    
    const allProducts = await storage.getProducts();
    const newProducts = allProducts.filter(product => {
      if (!product.createdAt) return false;
      const productDate = new Date(product.createdAt);
      productDate.setHours(0, 0, 0, 0);
      return productDate.getTime() === today.getTime();
    });

    if (newProducts.length > 0) {
      console.log(`${newProducts.length} ta yangi mahsulot topildi`);
      
      // Har bir yangi mahsulotni Telegram'ga yuborish
      for (const product of newProducts) {
        try {
          const { sendProductToChannel } = await import('../services/telegram-bot');
          await sendProductToChannel(product);
          
          // Mahsulotlar orasida 5 soniya kutish
          await new Promise(resolve => setTimeout(resolve, 5000));
        } catch (error) {
          console.error(`Mahsulotni yuborishda xatolik: ${product.nameUz}`, error);
        }
      }
    } else {
      console.log('Bugun yangi mahsulotlar qo\'shilmagan');
      
      // Agar yangi mahsulotlar bo'lmasa, tasodifiy mahsulotni "tavsiya" sifatida yuborish
      const featuredProducts = allProducts.filter(p => p.isFeatured && p.isActive);
      if (featuredProducts.length > 0) {
        const randomProduct = featuredProducts[Math.floor(Math.random() * featuredProducts.length)];
        
        try {
          const { sendProductToChannel } = await import('../services/telegram-bot');
          await sendProductToChannel(randomProduct);
          console.log(`Tavsiya etilgan mahsulot yuborildi: ${randomProduct.nameUz}`);
        } catch (error) {
          console.error('Tavsiya etilgan mahsulotni yuborishda xatolik:', error);
        }
      }
    }
  } catch (error) {
    console.error('Mahsulotlarni tekshirishda xatolik:', error);
  }
}

// Marketing xabarlarini yuborish funksiyasi
async function sendMarketingCampaign(storage: IStorage): Promise<void> {
  try {
    const marketingMessages = [
      {
        title: "🔥 MAXSUS CHEGIRMA!",
        content: `OptomBazar.uz da barcha plastik idishlar uchun 15% chegirma!
        
📅 Muddati: 3 kun
💰 Minimal buyurtma: 500,000 so'm
🚚 Bepul yetkazib berish Toshkent bo'ylab

Ushbu imkoniyatni boy bermang! Bugun buyurtma bering.`,
        imageUrl: null
      },
      {
        title: "🎯 YANGI MIJOZLAR UCHUN",
        content: `Birinchi buyurtmangizga 20% chegirma!

✅ Sifatli mahsulotlar
✅ Tez yetkazib berish  
✅ Professional xizmat
✅ Optom narxlar

Ro'yxatdan o'ting va chegirmangizni oling!`,
        imageUrl: null
      },
      {
        title: "📦 OMMABOP MAHSULOTLAR",
        content: `Eng ko'p sotilayotgan mahsulotlarimiz:

🥇 Polietilen paketlar - 25,000 so'm/kg dan
🥈 Bir martalik idishlar - 15,000 so'm/to'plam dan  
🥉 Plastik konteynerlar - 35,000 so'm/dona dan

Bugun buyurtma bering va eng yaxshi narxlardan foydalaning!`,
        imageUrl: null
      }
    ];

    // Tasodifiy marketing xabarini tanlash
    const randomMessage = marketingMessages[Math.floor(Math.random() * marketingMessages.length)];
    
    const { sendMarketingMessage } = await import('../services/telegram-bot');
    await sendMarketingMessage(randomMessage as any);
    
    console.log(`Marketing xabari yuborildi: ${randomMessage.title}`);
  } catch (error) {
    console.error('Marketing kampaniyasida xatolik:', error);
  }
}

// Asosiy scheduler funksiyasi
export function startBlogScheduler(storage: IStorage): void {
  if (isSchedulerActive) {
    console.log('Blog scheduler allaqachon faol');
    return;
  }

  console.log('Blog scheduler ishga tushirilmoqda...');
  
  // Har 2 soatda blog post yaratish (08:00 dan 20:00 gacha)
  cron.schedule('0 8-20/2 * * *', async () => {
    console.log('Blog post yaratish vazifasi boshlandi...');
    
    try {
      // O'zbek va rus tillarini navbat bilan tanlash
      const currentHour = new Date().getHours();
      const language = currentHour % 4 === 0 ? 'uz' : 'ru';
      
      await createAndSaveBlogPost(storage, language);
    } catch (error) {
      console.error('Blog post yaratishda xatolik:', error);
    }
  }, {
    timezone: "Asia/Tashkent"
  });

  // Har kuni ertalab soat 9:00 da yangi mahsulotlarni tekshirish
  cron.schedule('0 9 * * *', async () => {
    console.log('Kunlik mahsulot tekshiruvi boshlandi...');
    
    try {
      await checkAndSendNewProducts(storage);
    } catch (error) {
      console.error('Kunlik mahsulot tekshiruvida xatolik:', error);
    }
  }, {
    timezone: "Asia/Tashkent"
  });

  // Kechqurun soat 18:00 da qo'shimcha mahsulot reklamasi
  cron.schedule('0 18 * * *', async () => {
    console.log('Kechki mahsulot reklamasi boshlandi...');
    
    try {
      const allProducts = await storage.getProducts();
      const activeProducts = allProducts.filter(p => p.isActive);
      
      if (activeProducts.length > 0) {
        const randomProduct = activeProducts[Math.floor(Math.random() * activeProducts.length)];
        const { sendProductToChannel } = await import('../services/telegram-bot');
        await sendProductToChannel(randomProduct);
        console.log(`Kechki reklama yuborildi: ${randomProduct.nameUz}`);
      }
    } catch (error) {
      console.error('Kechki reklama yuborishda xatolik:', error);
    }
  }, {
    timezone: "Asia/Tashkent"
  });

  // Haftalik marketing kampaniyasi - har dushanba va juma 14:00 da
  cron.schedule('0 14 * * 1,5', async () => {
    console.log('Haftalik marketing kampaniyasi boshlandi...');
    
    try {
      await sendMarketingCampaign(storage);
    } catch (error) {
      console.error('Marketing kampaniyasida xatolik:', error);
    }
  }, {
    timezone: "Asia/Tashkent"
  });

  // Haftalik hisobot - har yakshanba 20:00 da
  cron.schedule('0 20 * * 0', async () => {
    console.log('Haftalik hisobot yuborish boshlandi...');
    
    try {
      const { sendWeeklyReport } = await import('../services/telegram-bot');
      await sendWeeklyReport();
    } catch (error) {
      console.error('Haftalik hisorot yuborishda xatolik:', error);
    }
  }, {
    timezone: "Asia/Tashkent"
  });

  // Oylik maxsus aksiya - har oyning 1-sanasida 10:00 da
  cron.schedule('0 10 1 * *', async () => {
    console.log('Oylik maxsus aksiya e\'lon qilinmoqda...');
    
    try {
      const { announceSpecialOffer } = await import('../services/telegram-bot');
      const nextMonth = new Date();
      nextMonth.setMonth(nextMonth.getMonth() + 1);
      
      await announceSpecialOffer({
        title: "OYLIK MAXSUS AKSIYA",
        description: "Ushbu oyda barcha mahsulotlarga maxsus chegirmalar! Optom xaridlar uchun qo'shimcha bonuslar.",
        discount: 20,
        validUntil: nextMonth,
        minOrder: 1000000
      });
    } catch (error) {
      console.error('Oylik aksiya e\'lon qilishda xatolik:', error);
    }
  }, {
    timezone: "Asia/Tashkent"
  });

  isSchedulerActive = true;
  console.log('Blog scheduler muvaffaqiyatli ishga tushirildi!');
  console.log('- Blog postlar: har 2 soatda (08:00-20:00)');
  console.log('- Yangi mahsulotlar: har kuni 09:00');
  console.log('- Kechki reklama: har kuni 18:00');
  console.log('- Marketing: dushanba va juma 14:00');
  console.log('- Haftalik hisorot: yakshanba 20:00');
  console.log('- Oylik aksiya: har oyning 1-sanasida 10:00');
}

// Scheduler'ni to'xtatish
export function stopBlogScheduler(): void {
  if (!isSchedulerActive) {
    console.log('Blog scheduler allaqachon to\'xtatilgan');
    return;
  }
  
  cron.getTasks().forEach((task, name) => {
    task.destroy();
  });
  
  isSchedulerActive = false;
  console.log('Blog scheduler to\'xtatildi');
}

// Test funksiyasi - darhol blog post yaratish
export async function createTestBlogPost(storage: IStorage, language: 'uz' | 'ru' = 'uz'): Promise<void> {
  console.log('Test blog post yaratilmoqda...');
  await createAndSaveBlogPost(storage, language);
}

// Test funksiyasi - darhol marketing xabari yuborish
export async function sendTestMarketingMessage(storage: IStorage): Promise<void> {
  console.log('Test marketing xabari yuborilmoqda...');
  await sendMarketingCampaign(storage);
}

// Scheduler statusini tekshirish
export function isSchedulerRunning(): boolean {
  return isSchedulerActive;
}
