import TelegramBot from 'node-telegram-bot-api';
import type { BlogPost, Product, MarketingMessage } from '@shared/schema';

// Telegram bot konfiguratsiyasi
const bot = new TelegramBot(process.env.TELEGRAM_BOT_TOKEN!, { polling: false });

// @optombazaruzb kanalining ID'si (botni kanalga admin qilib qo'shgandan keyin olinadi)
const CHANNEL_ID = process.env.TELEGRAM_CHANNEL_ID || '@optombazaruzb';

interface TelegramMessage {
  text: string;
  parse_mode?: 'HTML' | 'Markdown';
  reply_markup?: {
    inline_keyboard: Array<Array<{
      text: string;
      url: string;
    }>>;
  };
}

// Blog postini Telegram kanaliga yuborish
export async function sendBlogPostToChannel(blogPost: BlogPost): Promise<boolean> {
  try {
    const isAutoGenerated = blogPost.isAutoGenerated ? '🤖 ' : '';
    const languageFlag = blogPost.language === 'uz' ? '🇺🇿' : '🇷🇺';
    
    const message: TelegramMessage = {
      text: `${isAutoGenerated}${languageFlag} <b>${blogPost.title}</b>

${blogPost.excerpt || blogPost.content.substring(0, 200) + '...'}

📖 To'liq o'qish uchun saytimizga tashrif buyuring!

#OptomBazar #Blog ${blogPost.tags?.map(tag => `#${tag.replace(/\s+/g, '')}`).join(' ') || ''}`,
      parse_mode: 'HTML',
      reply_markup: {
        inline_keyboard: [[
          {
            text: '📖 To\'liq o\'qish',
            url: `https://optombazar.uz/blog/${blogPost.slug}`
          },
          {
            text: '🛒 OptomBazar',
            url: 'https://optombazar.uz'
          }
        ]]
      }
    };

    await bot.sendMessage(CHANNEL_ID, message.text, {
      parse_mode: message.parse_mode,
      reply_markup: message.reply_markup
    });

    console.log(`Blog post Telegram kanaliga yuborildi: ${blogPost.title}`);
    return true;
  } catch (error) {
    console.error('Blog postni Telegram kanaliga yuborishda xatolik:', error);
    return false;
  }
}

// Yangi mahsulotni Telegram kanaliga yuborish
export async function sendProductToChannel(product: Product): Promise<boolean> {
  try {
    const priceText = product.wholesalePrice !== product.price 
      ? `💰 Optom narxi: ${product.wholesalePrice} so'm\n📱 Chakana narxi: ${product.price} so'm`
      : `💰 Narxi: ${product.price} so'm`;

    const message: TelegramMessage = {
      text: `🆕 <b>YANGI MAHSULOT!</b>

🛍️ <b>${product.nameUz}</b>

📋 ${product.descriptionUz || product.nameRu}

${priceText}
📦 Minimal buyurtma: ${product.minQuantity} ${product.unit}
📊 Mavjud miqdor: ${product.stockQuantity} ${product.unit}

💼 Optom narxlarda xarid qiling!

#OptomBazar #YangiMahsulot #Optom`,
      parse_mode: 'HTML',
      reply_markup: {
        inline_keyboard: [[
          {
            text: '🛒 Xarid qilish',
            url: `https://optombazar.uz/products/${product.slug}`
          },
          {
            text: '📱 OptomBazar',
            url: 'https://optombazar.uz'
          }
        ]]
      }
    };

    // Mahsulot rasmi bo'lsa, uni bilan birga yuborish
    if (product.images && product.images.length > 0) {
      await bot.sendPhoto(CHANNEL_ID, product.images[0], {
        caption: message.text,
        parse_mode: message.parse_mode,
        reply_markup: message.reply_markup
      });
    } else {
      await bot.sendMessage(CHANNEL_ID, message.text, {
        parse_mode: message.parse_mode,
        reply_markup: message.reply_markup
      });
    }

    console.log(`Mahsulot Telegram kanaliga yuborildi: ${product.nameUz}`);
    return true;
  } catch (error) {
    console.error('Mahsulotni Telegram kanaliga yuborishda xatolik:', error);
    return false;
  }
}

// Marketing xabarini yuborish
export async function sendMarketingMessage(marketingMsg: MarketingMessage): Promise<boolean> {
  try {
    const message: TelegramMessage = {
      text: `📢 <b>${marketingMsg.title}</b>

${marketingMsg.content}

#OptomBazar #Marketing #Aksiya`,
      parse_mode: 'HTML',
      reply_markup: {
        inline_keyboard: [[
          {
            text: '🛒 OptomBazar saytiga o\'tish',
            url: 'https://optombazar.uz'
          }
        ]]
      }
    };

    // Marketing xabari rasmi bo'lsa
    if (marketingMsg.imageUrl) {
      await bot.sendPhoto(CHANNEL_ID, marketingMsg.imageUrl, {
        caption: message.text,
        parse_mode: message.parse_mode,
        reply_markup: message.reply_markup
      });
    } else {
      await bot.sendMessage(CHANNEL_ID, message.text, {
        parse_mode: message.parse_mode,
        reply_markup: message.reply_markup
      });
    }

    console.log(`Marketing xabari yuborildi: ${marketingMsg.title}`);
    return true;
  } catch (error) {
    console.error('Marketing xabarini yuborishda xatolik:', error);
    return false;
  }
}

// Bot ma'lumotlarini olish
export async function getBotInfo() {
  try {
    const botInfo = await bot.getMe();
    console.log('Telegram bot ma\'lumotlari:', botInfo);
    return botInfo;
  } catch (error) {
    console.error('Bot ma\'lumotlarini olishda xatolik:', error);
    throw error;
  }
}

// Kanalga test xabari yuborish
export async function sendTestMessage(): Promise<boolean> {
  try {
    const message = `🤖 <b>Test xabari</b>

OptomBazar.uz Telegram bot muvaffaqiyatli ishlayapti!

Vaqt: ${new Date().toLocaleString('uz-UZ')}

#Test #OptomBazar`;

    await bot.sendMessage(CHANNEL_ID, message, { parse_mode: 'HTML' });
    console.log('Test xabari muvaffaqiyatli yuborildi!');
    return true;
  } catch (error) {
    console.error('Test xabarini yuborishda xatolik:', error);
    return false;
  }
}

export { bot };